name: tutorial
version: 0.1.0.0

library:
  source-dirs: src
  dependencies:
    - base
    - text
    - bytestring

tests:
  simple-spec:
    dependencies:
      - base
      - text
      - bytestring
      - tutorial
      - hedgehog
    source-dirs:
      - test
    main: Spec.hs
